### ISSUE TITLE
Support grid paginator property

### ISSUE THREAD

**Issue by donvadicastro** [donvadicastro/meta-renderer-react#4]
```
name: list-bids
binding: bids
renderer: table
ui:
  rows: 5
  paginator: false
```

default if not specified - TRUE
